### ISSUE TITLE
Polynomial multiplication is often inaccurate

### ISSUE THREAD

**Issue by MadDataScientist** [Keno/Polynomials.jl#56]
Sometimes multiplying a polynomial p with another one, p_, may not yield the expected result. Here is a printout of a loop where a polynomial Pj is updated in every iteration. The new Pj does not always reflect the update:

```
2 -4.047588495693385e-21
2 -154.8971429 + x
2 6.269598936178143e-19
3 6.269598936178143e-19
3 -211.0 + x
3 -1.3228853755335882e-16
4 -1.3228853755335882e-16
4 -230.1282051 + x
4 3.044332370245841e-14
5 3.044332370245841e-14
5 -242.552795 + x
5 -7.384113253121036e-12 + 3.044332370245841e-14x
6 -7.384113253121036e-12 + 3.044332370245841e-14x
6 -257.96875 + x
6 1.904870465766067e-9 - 1.5237539414489605e-11x + 3.044332370245841e-14x^2
```

Here is the source code for this (c_ = some scalar value, x is a vector of data):

```jl
Pj = Poly([c_])	

for i in not_j
    println(i, " ", Pj)

    Pj *= Poly([-x[i], 1])

    println(i, " ", Poly([-x[i], 1]))
    println(i, " ", Pj)
end
```

**Comment by vtjnash** [comment]
Can you point out which value isn't computed correctly? They all look correct to me at first glance.

**Comment by pwl** [comment]
This is due to the somewhat arbitrary truncation in the constructor in 0.0.5 version.  It is already fixed in master:  the constructor no longer truncates the result of multiplication and there is an explicit `truncate` function which you can use if you need to.  See #38 for the discussion.  If you want to use the master branch run

```julia
julia> Pkg.checkout("Polynomials","master")
```
and restart julia.

**Comment by jverzani** [comment]
This branch just got tagged and published. Closing now.
